name: data_analysis
channels:
  - bioconda
  - asmeurer
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - matplotlib=2.2.2
  - numpy=1.14.2
  - pandas=0.23.4
  - python=2.7.14
  - scipy=1.0.0
  - seaborn=0.9.0
  - jupyter=1.0.0 
  - plotly=3.10.0 
